name: topnote
description: A Top Note app



publish_to: 'none'











version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"







dependencies:
  google_fonts: ^2.2.0
  flutter_screenutil: ^5.1.0
  flutter_bloc: ^8.0.1
  bloc: ^8.0.2
  hydrated_bloc: ^8.0.0
  hive: ^2.0.5
  hive_generator: ^1.1.2
  path_provider: ^2.0.8
  smooth_page_indicator: ^1.0.0+2
  equatable: ^2.0.3
  hive_flutter: ^1.1.0
  build_runner: ^2.1.7
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0





flutter:
  uses-material-design: true
  assets:
      - images/
